name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      env:
        PROSPECTOR_APPLICATION_ID: ${{ secrets.PROSPECTOR_APPLICATION_ID }}
        PROSPECTOR_BOT_TOKEN: ${{ secrets.PROSPECTOR_BOT_TOKEN }}
        PROSPECTOR_LAMBDA_EXECUTION_ROLE: ${{ secrets.PROSPECTOR_LAMBDA_EXECUTION_ROLE }}
        PROSPECTOR_PUBLIC_KEY: ${{ secrets.PROSPECTOR_PUBLIC_KEY }}
    - name: Run tests
      run: cargo test --verbose
