name: BotTests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always
  SOMMELIER_APPLICATION_ID: ${{ secrets.SOMMELIER_APPLICATION_ID }}
  SOMMELIER_BOT_TOKEN: ${{ secrets.SOMMELIER_BOT_TOKEN }}
  SOMMELIER_LAMBDA_EXECUTION_ROLE: ${{ secrets.SOMMELIER_LAMBDA_EXECUTION_ROLE }}
  SOMMELIER_PUBLIC_KEY: ${{ secrets.SOMMELIER_PUBLIC_KEY }}
  SOMMELIER_GAMBLING_SALT: ${{ secrets.SOMMELIER_GAMBLING_SALT }}

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Formatting
      run: cargo fmt --check
    - name: Build App
      run: cargo build --verbose
    - name: Test App
      run: cargo test --verbose
